spring:
  datasource:
    #数据源配置信息
    name: emis
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://emis-db:3306/emis?useUnicode=true&characterEncoding=utf8
    username: emisddl
    password: emisddl123
    driverClassName: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 1
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 10000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  rabbitmq:
    #mq配置信息
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0

logging:
  level:
    root: INFO
