spring:
  rabbitmq:
    host: mq
    port: 5672
    username: guest
    password: guest
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://emis_db:3306/emis?useUnicode=true&characterEncoding=utf8
    username: emisddl
    password: emisddl123
    initialize: true
zipkin:
  storage:
    type: mysql
